### ISSUE TITLE
Kodi veritabani

### ISSUE THREAD

**Issue by juk47ht** [RecNes/service.subtitles.planetdp_by_recnes#1]
Merhaba. Turkce altyazi alanindaki acigi kapattigin icin tesekkurler. Calisan bir planetdp eklentisini uzun zamandir bekliyordum. Acaba bu ve turkcealtyazi eklentisi kodi veritabanina yuklenecek mi? Bahsettigim veritabi su: https://kodi.tv/addons/browse?keyword=&category=1171&author=&sort=title+ASC

Kodi'ye add-on yukleme yontemi de soyle anlatilmis: http://kodi.wiki/view/Submitting_Add-ons

Bu issue'yu benzer bir baska uygulama icin de actim fakat oradaki gelistiriciden cevap alamadim.

Tesekkurler

**Comment by RecNes** [comment]
İlgin için teşekkür ederim,
Ancak henüz o açığı kapattım denemez. projeye başladım ancak şu an yoğunluktan dolayı devam edemiyorum. Umuyorum ki en kısa zamanda tekrar başına oturacağım.

Eklenti tamamlanınca tabi ki Kodi deposuna göndereceğim. Umarım kabul edilir ve yüklenir.
